### ISSUE TITLE
Data source references

### ISSUE THREAD

**Issue by saltcod** [ahmadawais/corona-cli#1]
Hey! This is fantastic! 

Would be great to see some detail about your data source(s), how quickly they are updated, when, etc.

Great work — thank you!

**Comment by ahmadawais** [comment]
Thank you! Please check out the sources here https://github.com/ahmadawais/corona-cli#license--conduct — every one of these are different.

**Comment by ahmadawais** [comment]
Also you query the live data whenever you run this CLI.
