### ISSUE TITLE
China & Italy not showing up in the list of all countries

### ISSUE THREAD

**Issue by TylerBarnes** [ahmadawais/corona-cli#10]
Hey there, thanks for this project. When you run `npx corona`, it appears the top 2 countries with the most cases (China and Italy) are missing from the top of the list.

**Comment by TylerBarnes** [comment]
You know what, I didn't realize it's sorted by cases today. My bad! Maybe a case for some ux improvement here though? Not sure

**Comment by ahmadawais** [comment]
It says right there about the sorting. And this is sort of a testament to
China having less cases than NY.

>
