### ISSUE TITLE
Name the used data source in the cli output

### ISSUE THREAD

**Issue by rpkoller** [ahmadawais/corona-cli#101]
it would be reasonable to name the data source for the displayed numbers on a cli output. if i take a look at the corona-cli source it seems it uses the worldometers data from the NOVELCovid/API... but since that API is also providing the sources from Johns Hopkins, New York Times and Apple it would be thoughtful and transparent to provide liner notes stating the utilization of the NOVELCovid/API and which of its provided sources is used. best regards ralf

**Comment by ahmadawais** [comment]
Sources are collectively attributed in the readme even though it's not required. For now I believe it's good enough.
