### ISSUE TITLE
Remove Scarf

### ISSUE THREAD

**Issue by Kurzdor** [ahmadawais/corona-cli#108]
https://github.com/final-form/react-final-form/issues/822
https://github.com/final-form/final-form/pull/361
https://github.com/tannerlinsley/react-query/issues/676

**Comment by ahmadawais** [comment]
How else do you think I can get to know what company is using this CLI so I can ask them to support my open source work?

**Comment by Kurzdor** [comment]
I would like to tell the **truth** but it will be better if I stay **silent**. Also do I need to teach that spamming companies asking for help is not quite good. Third, this is not the way forcing people to install it. For example, some Scarf users disabled it after 2 weeks of use of it.

Sorry if I am being rude, but if you really want people to hate you about using this lib then do it. The main my thoughts are https://github.com/scarf-sh/scarf-js/issues/24. Most users opted-out from it. They say it gave more than needed info so you should think. Some of them: final-form and its React connector, react-table, react-query, etc.

**Comment by ahmadawais** [comment]
After thinking about it for some time. I have removed Scarf. I wish npm/github would provide better analytics.

🔗 https://github.com/ahmadawais/corona-cli/releases/tag/5.3.3
🔗 https://www.npmjs.com/package/corona-cli

**Comment by Kurzdor** [comment]
@ahmadawais I understand you and I wish the same, mate =)
