### ISSUE TITLE
Output: json / report / dir

### ISSUE THREAD

**Issue by tunnckoCore** [ahmadawais/corona-cli#11]
Great one!

1. a JSON output (through `--json` flag?) would be good
2. A more clean output (only the table) would be good
2. Add the date (plus time) the command is run to the output
2. A `--top` flag or `--limit` one, to output only X number of countries.
  4.1. `corona --top 10` or `corona --limit 30` 
3. "Report" feature, behind `--report` flag, meaning it will write the table to file at some location (also customizable through flag). Like `./report/corona-iso-date.txt` (or `.json` if the (1) flag is present)
  5.1. `corona --json --report ./corona-foobar.json`
  5.2. `corona --json --report` -> to default location & default file name like `./report/corona-2020-04-21` with `.json` ext (because the `--json` flag, otherwise no)
  5.3. `corona --report` -> table output to default loc `./report/corona-2020-04-21`

This way we can collect the data for each day and do more interesting stuff later in time.

**Comment by ahmadawais** [comment]
👋 howdy!

Interesting ideas. I specifically like the reporting idea.

Feel free to help and contribute.

**Comment by mwherman2000** [comment]
Checkout https://github.com/ahmadawais/corona-cli/issues/58#issuecomment-606778151

**Comment by ahmadawais** [comment]
Already fixed in the latest release.
