### ISSUE TITLE
Suggestion: limit output to N countries

### ISSUE THREAD

**Issue by firasdib** [ahmadawais/corona-cli#16]
I'm mostly interested in looking at the progression of the disease in the current top 10 countries. Would it be possible to specify a cutoff number, where only the top `N` results are shown?

For example: `corona --sort cases -n 10`

**Comment by ahmadawais** [comment]
Good idea. I welcome your contributions to make this happen. Go ahead.

**Comment by firasdib** [comment]
Done.

**Comment by ahmadawais** [comment]
Implemented. Update the CLI: `npm i -g corona-cli`
