### ISSUE TITLE
Add "last updated" date to data returned from REST endpoint

### ISSUE THREAD

**Issue by smbyers** [ahmadawais/corona-cli#18]
Include the date when the data was last updated in the response from the REST endpoint at ttps://corona.lmao.ninja

**Comment by floturcocantsee** [comment]
Pull #20 adds this functionality at the end of the program's output. @smbyers

**Comment by smbyers** [comment]
I was interested in seeing the last updated from data source (https://corona.lmao.ninja) endpoint that is called by the CLI to understand when that data point came in.  It may also be valuable to see when the CLI was called but that does not tell the age of the actual data that is from the endpoint.

**Comment by floturcocantsee** [comment]
@smbyers the code gets the updated time from the API at this endpoint: https://corona.lmao.ninja/all.
Most of the code is just formatting and converting it out of the UNIX time stamp.

**Comment by smbyers** [comment]
@floturcocantsee I had been looking specifically by country and did not see a date.  I guess technically the date at the /all endpoint would be the last updated for all the data (meaning data does not come in at different times per country).

**Comment by floturcocantsee** [comment]
There is the endpoint provided for the data from John Hopkins University: https://corona.lmao.ninja/jhucsse.
Problem is I don't know if the data provided there is actually related to what the /countries endpoint produces.

**Comment by ahmadawais** [comment]
🐛 FIXED

🔗 https://github.com/ahmadawais/corona-cli/releases/tag/3.3.0
🔗 https://www.npmjs.com/package/corona-cli
