### ISSUE TITLE
Android App?

### ISSUE THREAD

**Issue by cbedoy** [ahmadawais/corona-cli#19]
Hi I was reading your code, and given read map it's a little complicated specially if you're on your phone, I thought to create an android app instead, what do you think?

I read your entry points doesn't need keys.

I created an android app that retrieve initially all the countries, are you agree?

There's the link and it's how it looks currently...

I hope you're ok.. 

![Android App](https://raw.githubusercontent.com/cbedoy/Corona-Tracker/master/demo.png)

Android App https://github.com/cbedoy/Corona-Tracker

**Comment by jeffersfp** [comment]
I like it!

**Comment by ahmadawais** [comment]
Thanks, I don't have an issue in general with that. But here are somethings that you _MUST_ change:

1. Remove this description from the readme and at the top of your repo and write your own description something like below:

**REMOVE*:* `Track the Coronavirus disease (COVID-19) or the Novel Coronavirus Strain in the command line. Both worldwide for all countries, for one country, or for the US States. Fast response time (< 100ms).`

**ADD**: Track Corona Virus COVID19 cases with this Andriod Application.

2. Add the corona-cli project in sources if possible (optional)

**Comment by cbedoy** [comment]
Done!
