### ISSUE TITLE
Cases (today) clarification

### ISSUE THREAD

**Issue by saltcod** [ahmadawais/corona-cli#2]
Me again!

Might be useful to clarify what "Cases (today)" actually means.  I'm assuming it's not in the past 24hrs, but rather it's comparing to a local timestamp?

Thanks!

**Comment by ahmadawais** [comment]
It's basically GMT based 24 hours records. E.g. March 20 (GMT) 24 hours are going to be called `Cases (today)` — has nothing to do with local timezones.

**Comment by ahmadawais** [comment]
New version has the key of data explanation at the bottom
