### ISSUE TITLE
reverse order of output

### ISSUE THREAD

**Issue by Integralist** [ahmadawais/corona-cli#23]
Great cli tool, thanks for sharing! ❤️ 

**Problem**: output of all countries is very long, requiring lots of scrolling to see top data
**Solution**: offer a `-r` flag to reverse the sort output order.

**Comment by ahmadawais** [comment]
PR welcomed.

**Comment by ahmadawais** [comment]
Implemented. Update the CLI: `npm i -g corona-cli`
