### ISSUE TITLE
Data in the wrong columns

### ISSUE THREAD

**Issue by kazungusafari** [ahmadawais/corona-cli#26]
![corona](https://user-images.githubusercontent.com/20744898/77342011-9b5b2e00-6d40-11ea-970c-3e66de1ef1d2.png)

**Comment by hiphotels** [comment]
+1

**Comment by ahmadawais** [comment]
Fixed in the major version release.

🔗 https://github.com/ahmadawais/corona-cli/releases/tag/3.0.0
🔗 https://www.npmjs.com/package/corona-cli
🏁 Done (in 27s.)
