### ISSUE TITLE
Table is broken

### ISSUE THREAD

**Issue by kseniaosipova** [ahmadawais/corona-cli#27]
The columns are broken now...

![image](https://user-images.githubusercontent.com/60135178/77341919-b5404500-6d2f-11ea-9eef-33343dc6ad3c.png)

**Comment by ahmadawais** [comment]
Thank you but I had already fixed it via filter across the files.

Update the CLI. It's been fixed already.

# Go ahead and run this:

```sh
npm i -g corona-cli
```
