### ISSUE TITLE
less verbose output

### ISSUE THREAD

**Issue by buckleyc** [ahmadawais/corona-cli#28]
Would be nice to have a slightly less verbose (i.e., more compact) output.
Workaround: this can be achieved by pipes (e.g. "| grep ...").

Would be nice to have option to remove empty lines between countries/states.
> --no-pad

Would be nice to have option to remove the Key.
> --no-key

Would be nice to remove the header ("Track the C...")
> --no-header

**Comment by ahmadawais** [comment]
PR welcomed for that.

**Comment by ahmadawais** [comment]
Implemented. Update the CLI: `npm i -g corona-cli`
