### ISSUE TITLE
Wrong column order

### ISSUE THREAD

**Issue by trungking** [ahmadawais/corona-cli#29]
The column order of country is wrong
![Annotation 2020-03-23 235720](https://user-images.githubusercontent.com/18730477/77341986-18e36600-6d62-11ea-9d19-3e2db9cd270c.png)

Try on both windows 10 and ubuntu

**Comment by ahmadawais** [comment]
FIXED!

🔗 https://github.com/ahmadawais/corona-cli/releases/tag/3.1.0
🔗 https://www.npmjs.com/package/corona-cli
