### ISSUE TITLE
Every stat is shifted to the right

### ISSUE THREAD

**Issue by hoob3rt** [ahmadawais/corona-cli#36]
Yesterday it was working fine and today it provides misleading data
![bug](https://user-images.githubusercontent.com/41551030/77371847-87292800-6d64-11ea-9c94-db2d790d2b9d.png)

**Comment by ahmadawais** [comment]
Update the CLI. It's been fixed already.

### Go ahead and run this:

```
npm i -g corona-cli
```

**Comment by ahmadawais** [comment]
Update the CLI. It's been fixed already.

# Go ahead and run this:

npm i -g corona-cli

>
