### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by shanereddy** [ahmadawais/corona-cli#43]
corona-cli is reporting 155 deaths for South Africa, this is incorrect. Deaths are zero today.
`corona South Africa`

**Comment by ahmadawais** [comment]
Report it to the source https://www.worldometers.info/coronavirus/

**Comment by shanereddy** [comment]
The source is correct. Your mapping of the fields has a bug.

<img width="988" alt="Screenshot 2020-03-25 at 20 04 50" src="https://user-images.githubusercontent.com/497848/77570103-ef4a4c00-6ed3-11ea-82a3-23c6024b1ab1.png">

<img width="966" alt="Screenshot 2020-03-25 at 20 03 35" src="https://user-images.githubusercontent.com/497848/77570126-f5d8c380-6ed3-11ea-8266-63c121ff448d.png">

**Comment by ahmadawais** [comment]
That's because you are reporting an issue without thinking that you might be using an older version and should update before creating an issue? So, yes `npm i -g corona-cli` a little bit more empathy to save time of a free and open source developer should be a welcomed sight here.

**Comment by shanereddy** [comment]
No disrespect man. I appreciate the module and your efforts.
Thanks for the feedback. An update fixed the issue.
