### ISSUE TITLE
corona help

### ISSUE THREAD

**Issue by LDdvlp** [ahmadawais/corona-cli#44]
At "CLI Help" section in the readme file, `corona help` is advised too, but only `corona --help` works, the error is " **Nops. A country named "help" does not exist…** ".
I was thinking `corona -h` but it is ignored, working like `corona`. 

LDdvlp.

**Comment by ahmadawais** [comment]
Are you sure you have the latest version of the CLI? The readme is up to date with the latest version. And it works there.
