### ISSUE TITLE
Incorrect (extra) column in output misrepresenting data

### ISSUE THREAD

**Issue by buckleyc** [ahmadawais/corona-cli#48]
The requested country has an extra column resulting in a deadly misrepresentation of data (i.e., deaths).
Note USA has an extra/blank column 2. This results in the subsequent columns being one off, thus reporting deaths as cases.

Example: "corona-cli usa"
> corona-cli  v2.5.0 by Awais.dev
> Track the Coronavirus disease (COVID-19).
> 
> 
> ┌───────────┬─────────┬───────────────┬────────┬────────────────┬───────────┬────────┬──────────┬─────────────┬─────────┐
> │ Country   │ Cases   │ Cases (today) │ Deaths │ Deaths (today) │ Recovered │ Active │ Critical │ Per Million │         │
> ├───────────┼─────────┼───────────────┼────────┼────────────────┼───────────┼────────┼──────────┼─────────────┤         │
> │ Worldwide │ 467,269 │ —             │ 21,160 │ —              │ 113,808   │ —      │ —        │ —           │         │
> ├───────────┼─────────┼───────────────┼────────┼────────────────┼───────────┼────────┼──────────┼─────────────┼─────┬───┤
> │ USA       │         │ 65,342        │ 10,486 │ 922            │ 142       │ 393    │ 64,027   │ 1,411       │ 197 │ 3 │
> └───────────┴─────────┴───────────────┴────────┴────────────────┴───────────┴────────┴──────────┴─────────────┴─────┴───┘
> 
>

**Comment by ahmadawais** [comment]
Before filing a bug it's important that you check if you are using the latest version of the CLI or not. I'm pretty sure you're on an older deprecated version.

### UPDATE `corona-cli` by running:

```sh
npm i -g corona-cli
```

Peace! ✌️
