### ISSUE TITLE
Add country code to country field

### ISSUE THREAD

**Issue by bdaase** [ahmadawais/corona-cli#5]
It would be nice to add the country code to the country field. This would help, to distinguish  between different countries more easily.

So, e.g. for China the country field would look like `China (CN)` instead of only showing `China`.

**Comment by ahmadawais** [comment]
Not sure what would that accomplish. It would make the CLI slow though. That's why I'm trying to avoid it. Right now you can search for the name of any country in your terminal. Care to share.

**Comment by Algebrista** [comment]
Awesome. I tried to check for Sierra Leone. But no result found. Is it that you tracking only countries that have reported a case thus far? If yes then it's okay but I suggest you change the message when a country with no recorded case is found instead of the current message. 

Thank you.
