### ISSUE TITLE
Wrong  per milion result

### ISSUE THREAD

**Issue by erropix** [ahmadawais/corona-cli#50]
![Annotation 2020-03-26 231936](https://user-images.githubusercontent.com/6576868/77702273-6e18b500-6fb8-11ea-910b-38577b8edb5f.png)

as shown in the above screenshot, the per million cases is wrong, for Italy and Spain

**Comment by joeguilmette** [comment]
Switzerland as well.

**Comment by JoseB91** [comment]
I think the problem is regarding the REST API, I looked on https://corona.lmao.ninja/v2/countries and is showing cases for all those countries you mentioned.

**Comment by ahmadawais** [comment]
Your screenshot doesn't show the version of CLI. Are you using the latest one?

**Comment by ahmadawais** [comment]
On the latest version of the CLI, I see all the correct stats

![image](https://user-images.githubusercontent.com/960133/81513424-d68ddc80-9341-11ea-85f9-87735e1013fa.png)

**Comment by erropix** [comment]
This was for the latest version at Mar 26 when I opened it

**Comment by ahmadawais** [comment]
What version? Is it 5.3? `corona --version` to check. As you see in my
screenshot, it's fine.

>

**Comment by erropix** [comment]
It's no longer an issue, I forgot the exact version, you can check what version was the latest as of March 26th. but anyway, it's surely was an API issue not related to the tool
