### ISSUE TITLE
Can we use this data in JSON?

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [ahmadawais/corona-cli#58]
Can we use this data in JSON? Can we use this data as API?

**Comment by mayeaux** [comment]
Same question, would be interesting to use it as a node module as opposed to a cli.

**Comment by mwherman2000** [comment]
If you look inside getWorldwide.js, etc., you'll see they use a web service that looks like [https://corona.lmao.ninja/all](https://corona.lmao.ninja/all) 

These web services return JSON.

**Comment by ahmadawais** [comment]
Feel free.

**Comment by mwherman2000** [comment]
p.s. I found the project for the above web service here: https://github.com/NovelCOVID/API

Documentation: https://docs.corona.lmao-xd.wtf/

**Comment by ayoubkhan558-zz** [comment]
I also found an API  😍 😘

`Get Stats by Country`
[Get Stats by Country](https://wp.xperts.club/covid19/wp-json/covid19/v1/country/CN)
`Get Stats`
[Get Stats](https://wp.xperts.club/covid19/wp-json/covid19/v1/datatables/confirmeddeathsrecovered?_=1586158028587)
`Get GLOBAL Stats by DATE`
[Get GLOBAL Stats by DATE](https://wp.xperts.club/covid19/wp-json/covid19/v1/country/GLOBAL)
`Map Stats`
[Map Stats](https://wp.xperts.club/covid19/wp-json/covid19/v1/map/)

😋 😎  :) Enjoy
