### ISSUE TITLE
can't install corectly

### ISSUE THREAD

**Issue by Aramdhann** [ahmadawais/corona-cli#59]
![image](https://user-images.githubusercontent.com/62165589/77838058-5dc03000-719a-11ea-9552-86387929acc7.png)

**Comment by viditvarshney** [comment]
try this command as sudo
 sudo npm install -g corona-cli

**Comment by nihitha582** [comment]
I had this issue initially as well, try running this command: sudo chown -R $USER /usr/local/lib/node_modules

**Comment by v1rtl** [comment]
that's not an issue with corona-cli, you have permissions set up not properly

**Comment by viditvarshney** [comment]
I think this issue is already solved @ahmadawais 
@Aramdhann please close it or share the further error if you got any

**Comment by Aramdhann** [comment]
thanks all, its work @viditvarshney
