### ISSUE TITLE
corona states no longer a command

### ISSUE THREAD

**Issue by DapperFox** [ahmadawais/corona-cli#64]
![Screen Shot 2020-03-31 at 9 04 58 AM](https://user-images.githubusercontent.com/2700294/78048587-c7714300-732e-11ea-9e24-c7b9afdd02d8.png)

When I run `corona states` with the latest version `0.9.0` I get:
`Country 'states' not found.`

**Comment by ahmadawais** [comment]
That's not the latest version. It's 30+ version after that. Update.  corona-cli  v3.8.6

**Comment by ahmadawais** [comment]
Before filing a bug it's important that you check if you are using the latest version of the CLI or not. I'm pretty sure you're on an older deprecated version.

### UPDATE `corona-cli` by running:

```sh
npm i -g corona-cli
```

Peace! ✌️

**Comment by DapperFox** [comment]
Ah, the package name change really threw me off. Thanks a lot! 👍

**Comment by ahmadawais** [comment]
Never changed the package name

>
