### ISSUE TITLE
npm test is failing

### ISSUE THREAD

**Issue by nisarhassan12** [ahmadawais/corona-cli#7]
`npm test` fails with the following error:

![Screenshot from 2020-03-21 12-31-09](https://user-images.githubusercontent.com/46004116/77221974-c000ab80-6b70-11ea-8a42-56d6526f406a.png)

I have tested this on:

1 - Arc Linux, Node 13
2 - Ubuntu, Node 10

**Comment by ahmadawais** [comment]
That's because no testing is set up yet.
