### ISSUE TITLE
Fails to sort on  -s cases_today

### ISSUE THREAD

**Issue by alf946** [ahmadawais/corona-cli#72]
corona-cli  v3.8.6 by Awais.dev
Track the Coronavirus disease (COVID-19).

  
ℹ Sorted by: cases_today
│ #   │ Country                          │ Cases     │ Cases (today) │ Deaths │ Deaths (today) │ Recovered │ Active  │ Critical │ Per Million │

│ —   │ Worldwide                        │ 1,215,940 │ —             │ 14,487 │ —              │ 65,666    │ —       │ —        │ —           │

│ 1   │ USA                              │ 311,637   │ 280           │ 8,454  │ 2              │ 14,828    │ 288,355 │ 8,206    │ 941         │

│ 2   │ Spain                            │ 130,759   │ 4,591         │ 12,418 │ 471            │ 38,080    │ 80,261  │ 6,861    │ 2,797       │

│ 3   │ Italy                            │ 124,632   │ 0             │ 15,362 │ 0              │ 20,996    │ 88,274  │ 3,994    │ 2,061       │

│ 4   │ Germany                          │ 96,108    │ 16            │ 1,446  │ 2              │ 26,400    │ 68,262  │ 3,936    │ 1,147       │

**Comment by Nezia1** [comment]
I think I fixed it. Just submitted a pull request!

**Comment by Nezia1** [comment]
Sorry, I mentioned the wrong issue when creating my pull request.

**Comment by nezia1** [comment]
Could you give more details on your issue?

**Comment by alf946** [comment]
The sorting was still by cases, even when using -s cases_today switch

**Comment by alf946** [comment]
so sorry, I thought the - was a _ 
it works as should
