### ISSUE TITLE
Hong Kong and Taiwan should be included in China

### ISSUE THREAD

**Issue by rangerzhou** [ahmadawais/corona-cli#82]
Hong Kong and Taiwan should be included in China，or you should be change table header Country to Country/Region, because they belong to China, not an independent country.

**Comment by Livinglist** [comment]
傻x吗，github又不是政治论坛，要改自己pr啊。

**Comment by ahmadawais** [comment]
https://twitter.com/MrAhmadAwais/status/1261799324230524929

**Comment by govi20** [comment]
How about Tibet then?

**Comment by rangerzhou** [comment]
> 傻x吗，github又不是政治论坛，要改自己pr啊。

sb，看不惯你来咬我？

**Comment by rangerzhou** [comment]
> https://twitter.com/MrAhmadAwais/status/1261799324230524929

@ahmadawais 
I like your project very much, just a rigorous suggestion, not related to politics, not just the countries and regions I mentioned, there may be other countries. Of course, you can decide whether to modify it yourself, and it will not affect your excellence. I will also like your project, and thank you for your contribution to everyone.

**Comment by Livinglist** [comment]
> > 傻x吗，github又不是政治论坛，要改自己pr啊。
> 
> 
> 
> sb，看不惯你来咬我？

我倒想看看你来咬我

**Comment by rangerzhou** [comment]
> > > 傻x吗，github又不是政治论坛，要改自己pr啊。
> > 
> > 
> > sb，看不惯你来咬我？
> 
> 我倒想看看你来咬我

2B
