### ISSUE TITLE
Support for node.js versions below 12

### ISSUE THREAD

**Issue by sampathBlam** [ahmadawais/corona-cli#83]
Great work, first of all !

I tried running corona-cli in my machine which has Node.js 10.16.3 (which isn't that old !! ) and found this error. 
```
× Node version issue!

You are running Node version: 10.16.3
Required version of Node is: 12 or higher.

i Please update your version of Node.js to run this program.

```
Is there any reason why corona-cli supports only Node.js versions 12 and higher? 
Is it possible to support lower versions?

**Comment by ahmadawais** [comment]
Not sure what would that accomplish. Currently 12.16.2 LTS is the long term support version behind that version are old versions not supported anymore, I don't want to maintain or support an old version of Node.js that's not active at all. You should probably upgrade to atleast v12.

**Comment by ahmadawais** [comment]
In all fairness, the CLI should work fine above v8 but I don't test features for anything below v12 so it's a hard bet.

**Comment by ahmadawais** [comment]
You could contribute a flag that would overrite this hard requirement at your own risk. Something like --dangerous -d command to signify it's unsafe to use old version and that flag would remove this check.

**Comment by sampathBlam** [comment]
@ahmadawais : Makes sense.

**Comment by sampathBlam** [comment]
@ahmadawais : Created a PR for an optional dangerous mode. Pls check.
