### ISSUE TITLE
no data being pulled via  v4.1.3 by Awais.dev

### ISSUE THREAD

**Issue by montyviz** [ahmadawais/corona-cli#89]
Can you let me know how to pull the data....on Powershell using >corona 
I get nothing but empty tables. Thoughts?

**Comment by SamuelMunoz** [comment]
Seems the api is down.

**Comment by ahmadawais** [comment]
Weird. Looking into it.

**Comment by ahmadawais** [comment]
🔗 https://github.com/ahmadawais/corona-cli/releases/tag/4.2.0
🔗 https://www.npmjs.com/package/corona-cli
🏁 Done (in 26s.)

API was updated and fixed. Please run `npm i -g corona-cli@latest` and it should be fixed.

**Comment by montyviz** [comment]
Thank you - I really appreciate your Api and got kinda hooked on it. Thanks
and stay safe out there.
Monty
