### ISSUE TITLE
It shows API is down if the country name includes spaces

### ISSUE THREAD

**Issue by DannyFeliz** [ahmadawais/corona-cli#96]
corona-cli version: v5.1.1
OS: Ubuntu 20.04
<hr>
If the country name has spaces it always shows  "⚠  API is down, try again later". It worked before at least in the early release of this CLI.
You can try with:

- Dominican Republic
- United Kingdom
- Central African Republic

![corona-cli](https://user-images.githubusercontent.com/5460365/80730729-f1598900-8ad7-11ea-8192-5ee7a6b2ba86.gif)

**Comment by ahmadawais** [comment]
You don't seem to be using the latest version, update and then report again if the issue is there.

**Comment by ahmadawais** [comment]
Most probably the name you are writing is wrong `corona "dominican republic"` works for me. Since there's a space there in the name put it inside `"…"` so that it is inerpretted as a single value.

**Comment by DannyFeliz** [comment]
@ahmadawais It works when it's wrapped in quotes 
`corona "dominican republic"`

Thanks
